# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: yes
    enp0s8:
      dhcp4: no
      addresses: [192.168.56.2/24]
      nameservers:
          addresses: [8.8.8.8, 4.4.4.4]
  version: 2
