- name: Update without taking into account the time zone
  become: yes
  command: apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false
  no_log: true

- name: Install aptitude
  apt:
    name: aptitude
    state: latest

- name: Update without taking into account the time zone
  become: yes
  command: apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false
  no_log: true

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update without taking into account the time zone
  become: yes
  command: apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false
  no_log: true

- name: Update apt and install docker-ce and docker-compose
  apt:
    name: 
      - docker-ce 
      - docker-compose
    state: latest

- name: Install Docker Module for Python
  pip:
    name: docker
