---
- name: Update without taking into account the timezone
  become: yes
  command: apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false
  no_log: true

- name: Install needed libraries
  become: yes
  become_user: root
  tags:
    - kernel
    - nginx
  apt:
    pkg:
      - nginx
      - nginx-extras
    state: present
    force: yes
