- name: Install bind9
  package:
    name:
      - bind9
      - bind9utils
      - bind9-doc
      - bind9-host
      - net-tools
    state: present

- name: /etc/bind/named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options

- name: /etc/bind/named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local

- name: /etc/systemd/resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf

- name: /etc/bind/db.robust.net
  template:
    src: db.robust.net
    dest: /etc/bind/db.robust.net
      
- name: open ports 53 to public
  ufw:
    rule: allow
    port: "53"
    proto: udp
  tags:
    - firewall

- name: Start service bind, if not started
  systemd:
    name: bind9
    state: restarted

- name: restart systemd-resolved service
  service:
    name: systemd-resolved.service
    state: restarted
