- name: add ssh key for cassa
  authorized_key:
    user: cassa
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+jk8LpXXoRHCZq59YZjcJmxV1RvwN3uChUCoUS95Wf ubuntu@ubuntuserver2204"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
