- name: install apache package
  tags: apache,ubuntu
  apt:
    name:
      - "{{ apache_package_name }}"
    state: latest
  when: ansible_distribution in ["Ubuntu"]

    #- name: start and enable apache service
    #  tags: apache,ubuntu
    #  service:
    #    name: "{{ apache_service }}"
    #    state: started
    #    enabled: yes

- name: copy default html file for site
  tags: apache,ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
