---
- name: "install Docker"
  hosts: docker
  become: yes

  pre_tasks:
    - shell: echo 'starting install'
  roles:
    - { role: docker }

  tasks:
    - shell: echo 'roles done'

  post_tasks:
    - shell: echo 'Install done'
